### ISSUE TITLE
Cannot run the lib on Linux

### ISSUE THREAD

**Issue by hntuan94** [TadLeonard/tfatool#17]
Hi @TadLeonard ,

Have you ever tried the lib on Linux?
I run the lib on Linux and get the following error:
```
HTTP request exception: HTTPConnectionPool(host='flashair', port=80): Max retries exceeded with url: /command.cgi?op=110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb62816b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
```
It may not be the lib's error but the 'urllib3'. How do you think?

**Comment by TadLeonard** [comment]
> Have you ever tried the lib on Linux?

I mostly run it on Linux. I've only done a tiny bit of non-Linux usage to test its compatibility with Windows. What do these commands show you?

1. `python --version` (just curious)
2. `cat /etc/resolve.conf`

You could try manually setting your nameserver to the [one specified here](https://www.flashair-developers.com/en/documents/api/config/), which I think is 192.168.0.1.

**Comment by hntuan94** [comment]
Hi @TadLeonard,

Thank you for your comment.
I used Python 3.5
Right now It works well. I just added the IP address of FlashAir in the CONFIG file then everything is OK.
